name: mix

on: [push, pull_request]

jobs:
  build:
    name: Elixir ${{matrix.elixir}} (Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pair:
              otp: 22.3
              elixir: 1.6.6
          - pair:
              otp: 24.2
              elixir: 1.13.4
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix do deps.get, compile
          mix compile
      - name: Run tests
        run: |
          mix credo --strict
          mix tests
          mix test
